name: air_pollution__adqh
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - rasterio=1.3.9
  - rasterstats=0.19.0
  - geopandas
  - pip
  - pip:
    - ipykernel
    - hydra-core
    - snakemake
    - tqdm
    - pyarrow
