defaults:
  - _self_
  - datapaths: zcta_cannon

#aqdh
url: "https://sedac.ciesin.columbia.edu/downloads/data/aqdh/aqdh-{pollutant_code}-concentrations-contiguous-us-1-km-v1-10-2000-2016/"
zip_filename: "aqdh-{pollutant_code}-concentrations-contiguous-us-1-km-v1-10-2000-2016-{yyyy}{mm}-geotiff"

pollutant_code_map:
  pm25: "pm2-5"
  o3: "o3"
  no2: "no2"
  

pollutant: "pm25" # "o3", "no2" 
yyyy: '2000'
mm: '02'
pollutant_code: "pm2-5"

tif_filename:
  pm25: PredictionStep2_PM25_USGrid_{yyyymmdd}_{yyyymmdd}
  o3: Ensemble_predictions_O3_USGrid_{yyyymmdd}_{yyyymmdd}
  no2: PredictionStep2_NO2_USGrid_{yyyymmdd}_{yyyymmdd}
 

shp_filename: us_shapefile__census__zcta_yearly__{yyyy}
shp_id: "zcta"

unique_id_filename: us_uniqueid__census__zcta_yearly__{yyyy}.parquet

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}