defaults:
  - _self_
  - datapaths: datapaths

#aqdh
url: "https://sedac.ciesin.columbia.edu/downloads/data/aqdh/aqdh-${pollutant}-concentrations-contiguous-us-1-km-v1-10-2000-2016/"
filename: "aqdh-{pollutant}-concentrations-contiguous-us-1-km-v1-10-2000-2016-{yyyymm}-geotiff"
pollutant: "pm2-5" # "o3", "no2" 
year: 2000
month: 1

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}