defaults:
  - _self_
  - datapaths: datapaths

#aqdh
url: "https://sedac.ciesin.columbia.edu/downloads/data/aqdh/aqdh-${pollutant}-concentrations-contiguous-us-1-km-v1-10-2000-2016/"
zip_filename: "aqdh-{pollutant}-concentrations-contiguous-us-1-km-v1-10-2000-2016-{yyyy}{mm}-geotiff"
pollutant: "pm2-5" # "o3", "no2" 
yyyy: '2000'
mm: '02'

tif_filename:
  o3: Ensemble_predictions_O3_USGrid_yyyymmdd_yyyymmdd
  no2: PredictionStep2_NO2_USGrid_20000101_20000101
  pm2-5: PredictionStep2_PM25_USGrid_yyyymmdd_yyyymmdd

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}