defaults:
  - datapaths: datapaths

#aqdh
url: "https://sedac.ciesin.columbia.edu/downloads/data/aqdh/aqdh-${pollutant}-concentrations-contiguous-us-1-km-v1-10-2000-2016/"
filename: "aqdh-${pollutant}-concentrations-contiguous-us-1-km-v1-10-2000-2016-${yyyymm}-geotiff.zip"
pollutant: "no2" # "o3", "pm2-5"
yyyymm: 200001  # Default value (you can override this dynamically)

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}